[build]
  publish = "Moviereview"

[[redirects]]
  from = "/api/*"
  to = "https://api.themoviedb.org/3/:splat"
  status = 200
  force = true
  [redirects.query]
    api_key = ":TMDB_API_KEY"